name: ZeloniaJoin
main: Main.Main
version: 1.0
author: NoriHD
commands:
  addtele:
    usage: /addtele
    description: Setzt ein Tele Point
    permission: zelonia.teletut
  deltele:
    usage: /deltele
    description: Loescht den zuletzt gesetzten Point.
    permission: zelonia.deltele